### ISSUE TITLE
Can't load urdf model

### ISSUE THREAD

**Issue by jkw0701** [humanoid-path-planner/hpp_tutorial#19]
Hi, 

I installed HPP 'development' version successfully.

Then, I started gepetto-gui and hpp-tutorial-server

I started hpp_tutorial/scripts/tutorial_1.py, the following error is came up

Error: hpp_idl.hpp.Error(msg='Unable to retrieve package://hpp_tutorial/urdf/pr2.urdf')

This error is also happened when I started hpp-rbprm-corba/script/scenarios/demos/darpa_hyq.py.

How can I fix this? 

Thanks in advance.

**Comment by florent-lamiraux** [comment]
Hello,

Make sure that you source config.sh in the terminal in which you run hppcorbaserver as well as in the terminal in which you run python.
If it does not work, send the result of command
`echo $ROS_PACKAGE_PATH`

**Comment by jkw0701** [comment]
Thank you for the reply.
I fixed the problem with setting bash.rc.

However, when starting any examples, 
codes can't load the instance of Robot(). 
Are there any issues to reference ?

Additionally, how can I recognize that the corba server successfully connect to gepetto?
The only command 'hpp-rbprm-server' is enough?

**Comment by florent-lamiraux** [comment]
I do not understand you question. Can you provide an error message ?

**Comment by jkw0701** [comment]
After launching gepetto-gui and server, 
I started tutorial_1.py.

In script, 2nd line 'robot=Robot('pr2')'
It did not respond and stopped for while.

**Comment by florent-lamiraux** [comment]
The problem comes from the fact that in default configuration, gepetto-gui tries to connect to some corbaservers that are not launched (manipulation part).

To avoid that, run
`gepetto-gui -c basic`
This will use the configuration file `$INSTALL_HPP_DIR/etc/gepetto-gui/basic.conf`.
Be sure that package `hpp-gui`is up to date (v4.6.0).

**Comment by jkw0701** [comment]
After installing hpp-gui, tutorial examples are successfully executed!

Thanks a lot!
