### ISSUE TITLE
the error: ``hppcorbaserver: command not found``.

### ISSUE THREAD

**Issue by EricWang1hitsz** [humanoid-path-planner/hpp_tutorial#23]
DONE:
1. Following the tutorial, I have set the ``bash`` as the default shell script language;
2.Add the ``source local/devel/hpp config.sh``to the .bashrc file.

ERROR:
I open the terminal and type ``hppcorbaserver``, but it appears the error: ``hppcorbaserver: command not found``.

I wonder why this error happens?

**Comment by jmirabel** [comment]
Did you add `export DEVEL_DIR=...` to your bashrc ?

**Comment by EricWang1hitsz** [comment]
Not yet, you mean that add``export DEVEL_DIR=/local/devel/hpp/install/bin``?

**Comment by jmirabel** [comment]
`export DEVEL_DIR=/local/devel/hpp`

**Comment by EricWang1hitsz** [comment]
I tried, but it didn't work.

**Comment by jmirabel** [comment]
```
export DEVEL_DIR=/local/devel/hpp
source local/devel/hpp/config.sh
```
should work. Check you environment variables.

**Comment by EricWang1hitsz** [comment]
I did it ! 
``hit@:~$ echo $PATH 
/install/sbin:/install/bin:/opt/ros/kinetic/bin:/home/hit/bin:/home/hit/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin``

``hit@:~$ echo $DEVEL_DIR 
/local/devel/hpp``

**Comment by jmirabel** [comment]
The variable is DEVEL_HPP_DIR, and not DEVEL_DIR. I messed up with old instructions.

**Comment by EricWang1hitsz** [comment]
It works! thanks very much!
